import product1 from '../assets/products/monitor.png'

export const products = [
    {
        id: 1,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 10,
        isLiked: false,
        isComparison: false,
        isNew: true,
        discount: 0,
        starRating: 3.5,

    },
    {
        id: 2,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 0,
        isLiked: false,
        isComparison: false,
        isNew: true,
        discount: 0.1,
        starRating: 0,
    },
    {
        id: 3,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 12,
        isLiked: false,
        isComparison: false,
        isNew: false,
        discount: 0,
        starRating: 4,
    },
    {
        id: 4,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 30,
        isLiked: false,
        isComparison: false,
        isNew: false,
        discount: 0.2,
        starRating: 2.5,
    },
    {
        id: 5,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 10,
        isLiked: false,
        isComparison: false,
        isNew: false,
        discount: 0.15,
        starRating: 3.5,
    },
    {
        id: 6,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 0,
        isLiked: false,
        isComparison: false,
        isNew: true,
        discount: 0,
        starRating: 0,
    },
    {
        id: 7,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 10,
        isLiked: false,
        isComparison: false,
        isNew: false,
        discount: 0.3,
        starRating: 5,
    },
    {
        id: 8,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 20,
        isLiked: false,
        isComparison: false,
        isNew: false,
        discount: 0.1,
        starRating: 3.5,
    },
    {
        id: 9,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 0,
        isLiked: false,
        isComparison: false,
        isNew: false,
        discount: 0,
        starRating: 0,
    },
    {
        id: 10,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 25,
        isLiked: false,
        isComparison: false,
        isNew: false,
        discount: 0.15,
        starRating: 4.5,
    },
    {
        id: 11,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 5,
        isLiked: false,
        isComparison: false,
        isNew: true,
        discount: 0,
        starRating: 3.5,
    },
    {
        id: 12,
        name: 'Монитор 23.8" Acer K240YB, Black (UM.QE0EE.B01)', 
        image: product1,
        price: 3500,
        numReview: 14,
        isLiked: false,
        isComparison: false,
        isNew: false,
        discount: 0.2,
        starRating: 3.5,
    },

]